### ISSUE TITLE
Exception in thread "Lunch RSP Server"

### ISSUE THREAD

**Issue by andreanaFelicione** [redhat-developer/vscode-rsp-ui#214]
I have the next exception when I open Visual Studio Code (I haven't entered any serverr yet, Red Hat Server Connector fails on start) :
```
Exception in thread "Launch RSP Server" 
java.lang.ExceptionInInitializerError
	at org.apache.felix.framework.URLHandlers.createURLStreamHandler(URLHandlers.java:513)
	at java.base/java.net.URL.getURLStreamHandler(URL.java:1465)
	at java.base/java.net.URL.<init>(URL.java:678)
	at java.base/java.net.URL.<init>(URL.java:568)
	at java.base/java.net.URL.<init>(URL.java:515)
	at org.jboss.tools.rsp.eclipse.jdt.launching.StandardVMType.getDefaultJavadocLocation(StandardVMType.java:683)
	at org.jboss.tools.rsp.eclipse.jdt.launching.StandardVMType.getDefaultJavadocLocation(StandardVMType.java:668)
	at org.jboss.tools.rsp.eclipse.jdt.launching.StandardVMType.getDefaultLibraryLocations(StandardVMType.java:440)
	at org.jboss.tools.rsp.launching.java.VMInstallClasspath.get(VMInstallClasspath.java:52)

	at org.jboss.tools.rsp.server.spi.launchers.AbstractJavaLauncher.getJREClasspath(AbstractJavaLauncher.java:195)
	at org.jboss.tools.rsp.server.spi.launchers.AbstractJavaLauncher.addJreClasspathEntries(AbstractJavaLauncher.java:199)
	at org.jboss.tools.rsp.server.wildfly.servertype.impl.WildFlyStartLauncher.getClasspath(WildFlyStartLauncher.java:48)
	at org.jboss.tools.rsp.server.spi.launchers.AbstractJavaLauncher.configureRunner(AbstractJavaLauncher.java:121)
	at org.jboss.tools.rsp.server.spi.launchers.AbstractJavaLauncher.getLaunchCommand(AbstractJavaLauncher.java:77)
	at org.jboss.tools.rsp.server.wildfly.servertype.AbstractJBossServerDelegate.updateDependentAttributes(AbstractJBossServerDelegate.java:414)
	at org.jboss.tools.rsp.server.wildfly.impl.ExtensionHandler$PostWildFlyCreationListener.serverAdded(ExtensionHandler.java:109)
	at org.jboss.tools.rsp.server.model.ServerModel.fireServerAdded(ServerModel.java:441)
	at org.jboss.tools.rsp.server.model.ServerModel.addServer(ServerModel.java:436)
	at org.jboss.tools.rsp.server.model.ServerModel.loadServers(ServerModel.java:206)
	at org.jboss.tools.rsp.server.model.ServerModel.loadServers(ServerModel.java:175)
	at org.jboss.tools.rsp.server.model.ServerPersistenceManager.loadState(ServerPersistenceManager.java:91)
	at org.jboss.tools.rsp.server.ServerManagementServerLauncher.launch(ServerManagementServerLauncher.java:93)
	at org.jboss.tools.rsp.server.ServerCoreActivator.lambda$1(ServerCoreActivator.java:58)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.RuntimeException: Unable to make protected boolean java.net.URLStreamHandler.equals(java.net.URL,java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @42110406
	at org.apache.felix.framework.URLHandlersStreamHandlerProxy.<clinit>(URLHandlersStreamHandlerProxy.java:104)
	... 24 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected boolean java.net.URLStreamHandler.equals(java.net.URL,java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @42110406
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at org.apache.felix.framework.util.SecureAction.setAccesssible(SecureAction.java:871)
	at org.apache.felix.framework.URLHandlersStreamHandlerProxy.<clinit>(URLHandlersStreamHandlerProxy.java:79)
	... 24 more
```

**Comment by robstryker** [comment]
In rsp-server, February 11th 2022, we upgraded from felix 6.0.3 to felix 7.0.3.  It was released on February 22nd. On April 5th, vscode-server-connector pulled in this newest rsp-server, which should have fixed this bug. 

Also I cannot replicate.
